#!/bin/python3

import mysql.connector

db_name = "translatedb"

"""
connection = mysql.connector.connect(
host="10.74.112.3",
user="root",
password=""
)
"""

with mysql.connector.connect(
    host="10.74.112.3",
    user="root",
    password=""
) as conn:

#cursor = connection.cursor()
    with conn.cursor() as cursor:
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {db_name}")

        cursor.execute(f"USE {db_name}")

        create_table_query = """
	        CREATE TABLE IF NOT EXISTS translations (
	        id INT AUTO_INCREMENT PRIMARY KEY,
	        input VARCHAR(255),
	        translation VARCHAR(255),
	        source VARCHAR(255),
	        target VARCHAR(255)
        )
        """
        cursor.execute(create_table_query)

"""
connection.commit()
connection.close()
"""

print("The database and table exist")
